Repository UnoYakshi/FPS-Prototype, pull requests merged in 2019-02, with the labels that each got.

#20 Bot that chases the player if sees one
  Content/ThirdPersonCPP/AI/BotBehaviorTree.uasset
  Content/ThirdPersonCPP/AI/BotBlackboardData.uasset
  Content/ThirdPersonCPP/AI/MyBot.uasset
  Content/ThirdPersonCPP/Maps/inner10range.umap
  Content/Weapons/AKSU-74/materials/M_KA74U.uasset
  Content/Weapons/AKSU-74/materials/M_KA74U_Gold.uasset
  Content/Weapons/AKSU-74/materials/M_KA74U_LeafSpray.uasset
  Content/Weapons/Master_Material/M_RDS_Master.uasset
  Source/Prot/AI/BTTargetPointSelection.cpp
  Source/Prot/AI/BTTargetPointSelection.h
  Source/Prot/AI/BotAIC.cpp
  Source/Prot/AI/BotAIC.h
  Source/Prot/Bot.h
Labels: ai

#21 2 bot behavior types
  Config/DefaultEngine.ini
  Content/ThirdPersonCPP/AI/AgressiveBotBehaviorTree.uasset
  Content/ThirdPersonCPP/AI/BotBehaviorTree.uasset
  Content/ThirdPersonCPP/AI/BotBlackboardData.uasset
  Content/ThirdPersonCPP/AI/CowardBotBehaviorTree.uasset
  Content/ThirdPersonCPP/AI/MyBot.uasset
  Content/ThirdPersonCPP/Maps/inner10range.umap
  Source/Prot/AI/BTRunPointSelect.cpp
  Source/Prot/AI/BTRunPointSelect.h
  Source/Prot/AI/BotAIC.cpp
  Source/Prot/Bot.h
Labels: ai

#27 AI shooting bots
  Content/ThirdPersonCPP/AI/AgressiveBotBehaviorTree.uasset
  Content/ThirdPersonCPP/AI/CowardBotBehaviorTree.uasset
  Content/ThirdPersonCPP/AI/MyBot.uasset
  Content/ThirdPersonCPP/AI/PatrolPointsBotBehaviorTree.uasset
  Content/ThirdPersonCPP/AI/RunFromPlayerBotBehaviorTree.uasset
  Content/ThirdPersonCPP/AI/ShootingBotBehaviorTree.uasset
  Content/ThirdPersonCPP/AI/UE4ASP_BotTPP_AnimBlueprint.uasset
  Content/ThirdPersonCPP/Maps/inner10range.umap
  Source/Prot/AI/BTRunPointSelect.cpp
  Source/Prot/AI/BotAIC.cpp
  Source/Prot/AI/BotAIC.h
  Source/Prot/AI/FireBTTaskNode.cpp
  Source/Prot/AI/FireBTTaskNode.h
  Source/Prot/AI/HasAmmoBTDecorator.cpp
  Source/Prot/AI/HasAmmoBTDecorator.h
  Source/Prot/AI/HasWeaponBTDecorator.cpp
  Source/Prot/AI/HasWeaponBTDecorator.h
  Source/Prot/AI/ReloadBTTaskNode.cpp
  Source/Prot/AI/ReloadBTTaskNode.h
  Source/Prot/Bot.cpp
  Source/Prot/Bot.h
  Source/Prot/HealthActorComponent.h
  Source/Prot/ProtCharacter.h
Labels: ai

#30 IK and Head Bobbing Camera Fixes
  Content/AnimStarterPack/Fire_Rifle_Ironsights.uasset
  Content/AnimStarterPack/UE4ASP_HeroTPP_AnimBlueprint.uasset
  Content/AnimStarterPack/UE4_Mannequin/Mesh/UE4_Mannequin_Skeleton.uasset
  Content/ThirdPersonCPP/Blueprints/ThirdPersonCharacter.uasset
  Content/ThirdPersonCPP/Maps/inner10range.umap
  Content/Weapons/AKSU-74/meshes/SK_KA74U_Y_Skeleton.uasset
  Source/Prot/MyPlayerController.cpp
  Source/Prot/MyPlayerController.h
  Source/Prot/Prot.h
  Source/Prot/ProtCharacter.cpp
  Source/Prot/ProtCharacter.h
Labels: animation, bug

#29 Fixed shooting bots
  Source/Prot/AI/BotAIC.cpp
  Source/Prot/AI/BotAIC.h
  Source/Prot/AI/FireBTTaskNode.cpp
  Source/Prot/AI/FireBTTaskNode.h
Labels: ai, bug
