Repository UnoYakshi/FPS-Prototype, pull requests merged in 2019-03, with the labels that each got.

#31 Added a simple mission
  .gitignore
  Config/DefaultEngine.ini
  Content/ThirdPersonCPP/Blueprints/MissionProtGameMode.uasset
  Content/ThirdPersonCPP/Blueprints/ThirdPersonCharacter.uasset
  Content/ThirdPersonCPP/Maps/MissionMap.umap
  Content/ThirdPersonCPP/Mission/MissionEndScriptedAction.uasset
  Content/ThirdPersonCPP/Mission/MissionProtGameMode.uasset
  Content/ThirdPersonCPP/Mission/MissionStartScriptedAction.uasset
  Content/ThirdPersonCPP/Mission/MyMission.uasset
  Prot.uproject
  Source/Prot/HealthActorComponent.h
  Source/Prot/Interactive/InteractiveObject.cpp
  Source/Prot/Interactive/InteractiveObject.h
  Source/Prot/Prot.h
Labels: gameplay

#33 Weapon to Component Transition
  Content/AnimStarterPack/Fire_Rifle_Ironsights.uasset
  Content/AnimStarterPack/UE4ASP_HeroTPP_AnimBlueprint.uasset
  Content/AnimStarterPack/UE4_Mannequin/Mesh/SK_Mannequin.uasset
  Content/AnimStarterPack/UE4_Mannequin/Mesh/UE4_Mannequin_Skeleton.uasset
  Content/ThirdPersonCPP/AI/MyBot.uasset
  Content/ThirdPersonCPP/AI/ShootingBotBehaviorTree.uasset
  Content/ThirdPersonCPP/AI/UE4ASP_BotTPP_AnimBlueprint.uasset
  Content/ThirdPersonCPP/Blueprints/ThirdPersonCharacter.uasset
  Content/Weapons/AKSU-74/meshes/SK_KA74U_X_Skeleton.uasset
  Content/Weapons/Weapon_BP.uasset
  Source/Prot/AI/BotAIC.cpp
  Source/Prot/AI/FireBTTaskNode.cpp
  Source/Prot/AI/ReloadBTTaskNode.cpp
  Source/Prot/ProtCharacter.cpp
  Source/Prot/ProtCharacter.h
  Source/Prot/Weapons/Magazine.h
  Source/Prot/Weapons/Weapon.cpp
  Source/Prot/Weapons/Weapon.h
  Source/Prot/Weapons/WeaponComponent.cpp
  Source/Prot/Weapons/WeaponComponent.h
Labels: bug, enhancement

#34 Hearing and aiming
  Content/ThirdPersonCPP/AI/BotBlackboardData.uasset
  Content/ThirdPersonCPP/AI/MyBot.uasset
  Content/ThirdPersonCPP/AI/ShootingBotBehaviorTree.uasset
  Content/ThirdPersonCPP/Maps/inner10range.umap
  Source/Prot/AI/BotAIC.cpp
  Source/Prot/AI/BotAIC.h
  Source/Prot/AI/FireBTTaskNode.cpp
  Source/Prot/Bot.cpp
  Source/Prot/Bot.h
  Source/Prot/ProtCharacter.cpp
  Source/Prot/ProtCharacter.h
  Source/Prot/Weapons/Weapon.cpp
  Source/Prot/Weapons/Weapon.h
Labels: ai
